### ISSUE TITLE
Feature Request: source for 1.20.1

### ISSUE THREAD

**Issue by klliio** [fingerguns83/Thoroughfabric#2]
Could you add the source for the 1.20.1 version or direct me to where it is available?

**Comment by fingerguns83** [comment]
Unfortunately there is no source for 1.20.1. I hadn't published the source at that point and I wasn't doing any version control; just building upon my existing code base. Best move is to pull the existing code, change the fabric/yarn versions and see what breaks. It's not a terribly complicated mod.
